FROM python:3.8.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get -y update
RUN apt-get -y install vim

RUN mkdir /srv/compose_test
ADD . /srv/compose_test

WORKDIR /srv/compose_test

RUN pip install --upgrade pip
RUN pip install -r requirements.txt




